name: Build

on:
  push:
    branches:
        - '**'

jobs:
  native-build:
    name: 'Native build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install Pino
      run: |
        declare -r PINO_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --url 'https://api.github.com/repos/AmanoTeam/Pino/releases/latest')")"
        declare -r PINO_TARBALL='/tmp/toolchain.tar.xz'
        declare -r PINO_URL="https://github.com/AmanoTeam/Pino/releases/download/${PINO_TAG}/x86_64-unknown-linux-gnu.tar.xz"
            
        curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${PINO_URL}" --output "${PINO_TARBALL}"
        tar --directory="$(dirname "${PINO_TARBALL}")" --extract --file="${PINO_TARBALL}"
            
        export PINO_HOME='/tmp/pino-toolchain'
        export PATH="${PINO_HOME}/bin:${PATH}"
        
        echo 'PINO_HOME=/tmp/pino' >> "${GITHUB_ENV}"
        echo 'PINO_STATIC=0' >> "${GITHUB_ENV}"
        
        echo '/tmp/pino/bin' >> "${GITHUB_PATH}"
    - name: Build prebuilts
      run: |
        bash 'main.sh'
    - name: Create release
      uses: softprops/action-gh-release@master
      with:
        tag_name: 0.1
        name: Pino Prebuilts
        files: ./*-linux-android*.tar.xz*
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        body: "* Initial release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
